server:
  error:
    whitelabel:
      enabled: false
  port: 8080
spring:
  data:
    redis:
      host: 13.124.94.213
      port: 6379
    mongodb:
      uri: mongodb://lotteon:Alcls154*@13.124.94.213:27017/lotteon?authSource=admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Alcls154*
    url: jdbc:mysql://13.124.94.213:3306/lotteon?useSSL=false&allowPublicKeyRetrieval=true
    username: lotteon
  devtools:
    livereload:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: bqho rwrc qkhg yyjq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
    username: sanghun1101088@gmail.com
  application:
    name: lotteon
    version: 0.0.6-SNAPSHOT
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

file:
  upload-dir: /home/ubuntu/upload
logging:
  file:
    name: /logs/lotteon.log
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: info
        sql: debug
      mybatis: error
      springframework:
        security: debug
        web: error
    root: info
kakao:
  client_id: 21f13935510b320e93de9c06c918e6ec
  redirect_uri: http://localhost:8080/auth/kakao/callback